name: DynamicStringLibrary Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test-and-sanitize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Valgrind
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind

    - name: Install static analyzers
      run: sudo apt-get install -y cppcheck

    - name: Run Cppcheck
      run: make cppcheck

    - name: Clean and Build Static/Shared Library
      run: |
        make clean
        make all CC=${{ matrix.compiler }}

    - name: Build Standard Tester
      run: make test CC=${{ matrix.compiler }}

    - name: Run Standard Suite
      run: ./tester

    - name: Build & Run with AddressSanitizer
      run: |
        ${{ matrix.compiler }} -std=c11 -Wall -Wextra -fsanitize=address,undefined tester.c dstr.c -o tester_asan
        ./tester_asan

    - name: Run Valgrind Memory Leak Check
      run: |
        valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./tester
