name: Clang Format Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Clang-Format 22
      run: |
        sudo apt-get update
        sudo apt-get install -y wget software-properties-common gnupg
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 22
        sudo apt-get install -y clang-format-22
        sudo ln -sf /usr/bin/clang-format-22 /usr/bin/clang-format

    - name: Check formatting
      run: make format-check
